define({
    'menu-search': 'Search',
    'menu-lightroom': 'Lightroom',
    'menu-map': 'Map',
    'menu-collections': 'My Workspace',
    'menu-timeline': 'Timeline',
    'menu-network': 'Network',
    'menu-share': 'Share',
    'results-for': 'Results for',
    'previous': 'Previous page',
    'navigateAwayMessage': 'You are about to leave Phaidra+!',
    'next': 'Next page',

    'slideshow-paralell-view' : "Split view",
    'slideshow-single-view' : "Single image",


    "moreentries":              "more entries",
    "deleteItem":               "Delete item from folder",
    'collectionsTitle':         "My folders",
    'objectsTitle':             "My objects",
    'currentObjectsTitle':      "New objects in phaidra+",
    'findObjectsTitle':         'Search objects',
    'collectionAdd': "Create new folder",
    'collectionOpen':"Open folder in lightroom",
    'collectionEdit' :'Edit folder',
    'collectionDelete' :'Delete folder',
    'object' :      'object',
    'objects' :         'objects',


    'myCollections':     "My Folders",
    'metadata-categories-title':     "Categories",
    'metadata-copyrights-title':     "Copyrights and Licenses",
    'metadata-objectdata-title':     "Further Objectdata",
    'metadata-otherdata-title': 'Other object data',
    'metadata-objecthistory-title':     "Object History",
    'metadata-attributions-title':      'Attributions',


    "actionsMenuAddtoCollection": "Add to my folders",
    "actionsMenuAddtoPresention": "Add this to my presentation",
    "actionsMenuCalltoAction": "Actions for this object",
    "actionsMenuMarkObject": "Mark this object",
    "actionsMenuShowAnnotations": "See the annotations",
    "actionsMenuShowNetwork": "See the object's network",
    "actionsMenuShowSimilar": "See similar object",
    "actionsMenuUnmarkObject": "Delete marker",
    "altTitleBefore": "Alternative",
    "byArtist": "by",
    "byAuthor": "Author",
    "singleViewCloseBtnTitle": "Close view",

    'show-title':"Title",
    'show-desc':"Description",

    "addToCollection": "Add to a folder",
    "downloadImage": "Download image",
    "openImage": "Display details",
    "markImage": "Mark this object",
    "author": "Author",
    "clearSelection": "Clear selection",
    "description": "Description",
    "display": "Display",
    "displayMode": "Mode",
    "filterByKeywords": "Filter by keywords",
    "filterByMarks": "Show only selected",
    "markAllObjects": "Mark all objects",
    "imageSize": "Image size",
    "invertSelection": "Invert selection",
    "list": "List",
    "markedImages": "Selected Images",
    "off": "Off",
    "on": "On",
    "showAll": "show all",
    "slideshow": "Slideshow",
    "tableau": "Table",
    "title": "Title",

    'afterThisDate': 'younger than',
    'alttitle' : 'alternative title',
    'author' : 'author',
    'beforeThisDate': 'older than',
    'booleanAnd': 'and',
    'booleanOr': 'or',
    "bye": "bye bye",
    "cancel": "cancel",
    'close': 'close',
    'copyright': 'copyright',
    'costs' : 'costs',
    'coverage': 'coverage',
    'datapool': 'datapool',
    'desc': 'description',
    'equalTo': 'equal to =',
    'filesize': 'filesize',
    'greaterThan': 'greater than >',
    'height': 'height',
    'image_height': 'Height (px)',
    'image_width': 'Width (px)',
    'identifiers': 'identifiers',
    'inscription': 'inscription',
    'keywords': 'keywords',
    'subtitle_de': 'Subtitle',
    'title_de': 'Title',
    'lessThan': 'smaller than <',
    'license': 'license',
    'login': 'Login',
    'logout': 'Logout',
    'members': 'members',
    'obj_date': 'date of the object',
    'onThisDate': 'exactly on',
    "ok": "ok",
    'password': 'Password',
    'peer_reviewed': 'peer reviewed',
    'pid': 'persistent ID',
    'please-login': 'Please login',
    'please-select': 'Please select',
    'PPT-creation-explanation': 'You can download this folder as a Powerpoint presentation. Please notice: the number of images is limited to 50. Click "create" to proceed!',
    'PPT-download-title': 'Create a Powerpoint Presentation',
    'query': 'search query',
    'search-select-label': 'Add a new search filter',
    'share-explanation': 'Use this link to share the current view.',
    'share-modal-title': 'Share this',
    'download-modal-title': 'Download image',
    'download-original':"Original image",
    'download-large':"Large",
    'download-medium':"Medium",
    'download-small':"Small",
    'start-search': 'search',
    'status': 'status',
    'subject': 'keyword',
    'subtitle': 'subtitle',
    'title': 'title',
    'type': 'type',
    'username': 'Username',
    "welcome": "welcome",
    'width': 'width',


    prefixAgo: null,
    prefixFromNow: null,
    suffixAgo: "ago",
    suffixFromNow: "from now",
    inPast: 'any moment now',
    seconds: "less than a minute",
    minute: "about a minute",
    minutes: "%d minutes",
    hour: "about an hour",
    hours: "about %d hours",
    day: "a day",
    days: "%d days",
    month: "about a month",
    months: "%d months",
    year: "about a year",
    years: "%d years",
    wordSeparator: " ",
    numbers: []

});