define({
  "root": {

    'menu-search': 'Suche',
    'menu-lightroom': 'Leuchttisch',
    'menu-geo': 'Landkarte',
    'menu-collections': 'Arbeitsplatz',
    'menu-timeline': 'Zeitleiste',

    'menu-semantic': 'Netzwerk',
    'menu-share': 'Teilen',
    'menu-share-desc': 'Diese Ansicht teilen',
    'results-for': 'Ergebnisse für',
    'previous': 'Vorherige Seite',
    'navigateAwayMessage': 'Sie sind dabei aus Phaidra+ auszusteigen!',
    'navigateLoginMessage': '',
    'next': 'Nächste Seite',
    'results':'Ergebnisse',
    'no-results':'Keine Ergebnisse',
    'menu-marker':"Auswahlmenü",
    "display-options-title": "Darstellung",
    "display-options": "Darstellungoptionen",

    'main-menu':"Darstellungsmenü",
    'marker-actions':"Auswahlmenü",

    'display-slideshow' : "Slideshow",
    'slideshow-paralell-view' : "Parallelprojektion",
    'slideshow-single-view' : "Einzelbild",

    'queryterm-field':'Suche',
    'help-queryterm-field':'Die Suchfunktion erlaubt Zugriff auf alle über Phaidra+ aufrufbaren digitalen Objekte.',

    'help-menu-collections':'Hier können Sie ihre virtuellen Ordner verwalten und haben Zugriff auf Ihre eigenen Objekte.',
    'my-collections':"Meine Ordner",
    'help-my-collections':'Speichern und verwalten Sie Ihre Recherchen und Präsentationen über virtuelle Ordner.',
    'my-objects-title':"Meine Objekte",
    'help-my-objects-title':'Ihre eigenen Objekte, die Sie in Phaidra oder PhaidraTemp abgelegt haben, finden Sie in diesem Bereich chronologisch sortiert.',

    
    'help-display-options':'Sie können Größe der angezeigten Objekte verändern und Titel sowie Beschreibung ein- oder ausblenden.',
    'help-menu-geo': 'Bei der Funktion Landkarte werden Ihre Objekte auf einer virtuellen Landkarte räumlich zugeordnet. Das ist jedoch nur dann möglich, wenn die entsprechenden Metadaten vergeben wurden. Hier steht Ihnen auch eine Filterfunktion nach bestimmten Begriffen zur Verfügung.',
    'help-menu-lightroom':'Der Leuchttisch zeigt Ihnen Ihre Objekte in Tableau- oder Listenform. Sie können von hier aus aber auch Objekte in der Vollansicht anzeigen, sie zu einem Ordner hinzufügen, downloaden oder markieren',
    'help-menu-timeline':'Hier werden Ihre Objekte entlang einer Zeitleiste dargestellt. Dies funktioniert jedoch nur, wenn das Datumsfeld in den Metadaten entsprechend ausgefüllt wurde.',
    'help-menu-semantic':'Sie finden hier eine Visualisierung der semantische Verknüpfung Ihrer Objekte. Auf der rechten Seite kann die Visualisierung verschoben und vergrößert werden. Sie können in das Netz hineinzoomen und mit einer Lupe die Objekte vergrößern.',
    'help-display-slideshow':'Die Funktion Slideshow ermöglicht Ihnen die Darstellung von Einzelbildern oder von zwei Bildern gleichzeitig.',
    'help-marker-actions':"Funktionen zur Arbeit mit einer Auswahl der dargestellten Objekte.",
    'help-main-menu':"Suchergebnisse und die Inhalte Ihrer Ordner können mit unterschiedlichen Darstellungsformen angezeigt werden.",
    'help-menu-share':"Hier können Sie die aktuell dargestellten Objekte mit anderen teilen.",

    'continue-tour':"Weiter",
    'finish-tour':"Tour beenden",
    'tour-collections-end':'Beginnen Sie mit dem Erstellen eines neuen Ordners und führen Sie anschließend eine Suchabfrage durch, um weitere Funktionen kennenzulernen.',
    'help-login-button':'Im angemeldeten Modus erhalten Sie mit Ihrem u:account Zugriff auf Ihren persönlichen Arbeitsplatz und weitere Funktionen von Phaidra+.',

    'create-new-collection':"Neue",


    "moreentries":        "weitere Einträge",
    "deleteItem":         "Aus dem Ordner entfernen",
    'collectionsTitle':     "Meine Ordner",
    'objectsTitle':     "Meine Objekte",
    'currentObjectsTitle':    "Neue Objekte in phaidra+",
    'findObjectsTitle':     'Objekte suchen',
    'collectionAdd':      "Neu",
    'new-collection': 'Neuer Ordner',
    'untitled-collection': 'Unbenannter Ordner',
    'collectionAddTooltip':      "Neuen Ordner anlegen",
    'untitledCollection':      "Unbenannt – zum Bearbeiten anklicken",
    'click-to-edit':      "Neuer Ordner",
    'collectionOpen':       "Ordner öffnen",
    'objectsOpen':       "Eigene Objekte öffnen",
    'collectionEdit' :      'Ordner bearbeiten',
    'collectionunEdit' :      'Bearbeitung beenden',
    'download-ppt' :      'Powerpoint herunterladen',
    'new-object': 'Neues Objekt',

    'objectAdd':      "Neu",
    'objectAddTooltip':      "Neues Objekt erstellen",
    'ingest-modal-title': "Neues Objekt erstellen",
    'ingest-modal-explanation': "<p>Neue Objekte können Sie in folgenden beiden System erstellen:<br>a) In PhaidraTemp – für die temporäre Ablage und Nutzung ihrer digitalen Objekte, die Sie zu einem späteren Zeitpunkt wieder löschen oder auch in Phaidra langzeitarchivieren können, z.B. im Bereich Forschung und Lehre.<br>b) Im Langzeitarchivierungssystem Phaidra – zur permanenten Speicherung Ihrer digitalen Objekte (z.B. Daten aus abgeschlossenen Forschungsprojekten)<br></p><p>Nach dem Upload Ihrer digitalen Objekte in einem der beiden Systeme stehen Ihnen diese, nach einer kurzen Wartezeit, auch in Phaidra+ zur Verfügung.</p>",
    'ingest-modal-link-phaidra-temp': "Upload in PhaidraTemp",
    'ingest-modal-link': "Upload in Phaidra",
    
    
    'collectionDelete' :    'Ordner löschen',
    'delete-warning' :    "Wollen Sie diesen Ordner löschen?",

    'object' :    'Objekt',
    'objects' :     'Objekte',
    'undatedObjects' :     'Objekte ohne Zeitangaben',
    'unlocatedObjects' :     'Objekte ohne geografische Angaben',
    'objects-not-placeable':"Diese Objekte können in dieser Ansicht aufgrund fehlender Metadaten (Zeit, Ort) nicht eingeordnet werden",



    
    'metadata-categories-title':     "Kategorien",
    'metadata-copyrights-title':     "Copyrights und Lizenzen",
    'metadata-objectdata-title':     "Objektdaten",
    'metadata-otherdata-title': 'Weitere Objektdaten',
    'metadata-objecthistory-title':     "Provenienz",
    'metadata-attributions-title':      'Schlagworte',
    'myCollections':     "Meine Ordner",
    'open-in-phaidra':     "in Phaidra öffnen",
    'open-in-phaidra-temp':     "in PhaidraTemp öffnen",
    
    'open-document': 'Dokument in neuem Fenster öffnen',
    'open-original-prefix': '',
    'open-original-postfix': "öffnen",



    "actionsMenuAddtoCollection": "Zu Ordner hinzufügen",
    "actionsMenuAddtoPresention": "add this to my presentation",
    "actionsMenuCalltoAction": "Aktionen für dieses Objekt",
    "actionsMenuMarkObject": "Auswählen",
    "actionsMenuUnmarkObject": "Auswahl entfernen",
    "actionsMenuShowAnnotations": "Annotationen anzeigen",
    "actionsMenuShowSimilar": "Ähnliche Bilder anzeigen",
    "altTitleBefore": "Alternativ ",
    "byArtist": "von",
    "byAuthor": "Autor",
    "singleViewCloseBtnTitle": "Ansicht schließen",

    'show-title':"Titel",
    'show-desc':"Beschreibung",


    "addToCollection": "Zu Ordner hinzufügen",
    "downloadImage": "Bild herunterladen",
    "downloadObject": "Objekt herunterladen",
    "openImage": "Vollansicht",
    "markObject": "Auswählen",
    "unmarkObject": "Auswahl entfernen",
    "author": "Autor",
    "clearSelection": "Zurücksetzen",
    "description": "Beschreibung",
    "display": "Anzeige",
    "displayMode": "Darstellung",
    "filterByKeywords": "Nach Begriffen filtern",
    "filterByMarks": "Filtern",
    "markAllObjects": "Alle auswählen",
    "imageSize": "Bildgröße",
    "invertSelection": "Umkehren",
    "list": "Liste",
    "markedImages": "Objekte ausgewählt",
    "marked-menu":"Auswahl",
    "off": "Aus",
    "on": "An",
    "showAll": "Alle anzeigen",
    "tableau": "Tableau",
    "title": "Titel",


    'afterThisDate': 'jünger als',
    'alttitle' : 'Alternativer Titel',
    'author' : 'Autor',
    'beforeThisDate': 'älter als',
    'booleanAnd': 'und',
    'booleanOr': 'oder',
    "bye": "Auf Wiedersehen",
    "cancel": "Abbrechen",
    'close': 'Schließen',
    'copyright': 'Copyright',
    'yes': 'Ja',
    'no': 'Nein',
    'costs' : 'Kosten',
    'coverage': 'Gültigkeit',
    'datapool': 'Datenpool',
    'desc': 'Beschreibung',
    'equalTo': 'gleich =',
    'filesize': 'Dateigröße',
    'filesize_human': 'Dateigröße',
    'greaterThan': 'größer als >',
    'image_height': 'Höhe (px)',
    'image_width': 'Breite (px)',
    'height': 'Höhe',
    'width': 'Breite',
    'source': 'Quelle',
    'measurement': 'Maße',
    'length': 'Länge',
    'identifiers': 'Datenkennung',
    'inscription': 'Inschrift',
    'keywords': 'Stichwörter',
    'language' :'Sprache des Objekts',
    'desc_language':"Sprache der Beschreibung",
    'upload_date':"Erstellungsdatum des digitalen Objekts",
    'title_languages':"Sprache(n) des Titels",
    'costs':"Kosten",
    'taxon':"Begriffe",
    'mimetype':"Dateityp",
    'pid':'identifiers',
    'coverage':"Zeitliche und/oder geografische Abdeckung",

    'lessThan': 'kleiner als <',
    'license': 'Lizenz',
    'login': 'Anmelden',
    'loginUseAccountMessage':'Bitte verwenden Sie zum Anmelden Ihren u:account',
    'authErrorMessage': 'Anmeldung fehlgeschlagen, bitte überprüfen Sie Ihre Angaben.',

    'login-button': 'Anmelden',
    'logout': 'Abmelden',
    'members': 'Mitglieder',

    'obj_date': 'Objektdatum',
    'onThisDate': 'exakt vom',
    "ok": "Ok",
    'password': 'Passwort',
    'peer_reviewed': 'peer reviewed',
    'pid': 'Permanente ID',
    'please-login': 'Bitte melden Sie sich an',
    'please-select': 'Bitte auswählen',

    'PPT-creation-explanation': 'Sie können ihren Ordner als Powerpoint Präsentation herunterladen.<br>Die Anzahl der Bilder ist hierbei auf 50 limitiert.',
    'PPT-download-title': 'Powerpoint Präsentation erstellen',
    'create-PPT': "Powerpoint erstellen",

    'query': 'Einfache Suche',
    'extended-search':"Erweiterte Suche",
    'search-select-label': 'Neuen Suchfilter hinzufügen',
    'share-explanation': 'Nutzen Sie diesen Link um die aktuelle Ansicht zu teilen.',
    'share-modal-title': 'Ansicht teilen',
        
    'collection-modal-title': 'Objekt zu Ordner hinzufügen',

    'download-modal-title': 'Bild herunterladen',
    'download-original':"Originalbild",
    'download-original-file':"Datei herunterladen",
    'download-large':"Groß",
    'download-medium':"Mittel",
    'download-small':"Klein",
    'start-search': 'Suche starten',

    'status': 'Status',
    'subject': 'Schlagwort',
    'subtitle': 'Untertitel',
    'subtitle_de': 'Untertitel',
    'title': 'Titel',
    'title_de': 'Titel',
    'type': 'Typ',
    

    'username': 'Benutzername',


     prefixAgo: null,
      prefixFromNow: null,
      suffixAgo: "vor",
      suffixFromNow: "in",
      inPast: 'gleich',
      seconds: "weniger als eine Minute",
      minute: "ungefähr eine Minute",
      minutes: "%d Minuten",
      hour: "ungefähr eine Stunde",
      hours: "ungefähr %d Stunden",
      day: "ein Tag",
      days: "%d Tage",
      month: "ungefähr ein Monat",
      months: "%d Monate",
      year: "ungefähr ein Jahr",
      years: "%d Jahre",
      wordSeparator: " ",
      numbers: []

  },
  "en": true
});