define({
  "root": {

    'menu-search': 'Suche',
    'menu-lightroom': 'Leuchttisch',
    'menu-map': 'Landkarte',
    'menu-collections': 'Arbeitsplatz',
    'menu-timeline': 'Zeitleiste',
    'menu-network': 'Netzwerk',
    'menu-share': 'Teilen',
    'menu-share-desc': 'Diese Ansicht teilen',
    'results-for': 'Ergebnisse für',
    'previous': 'Vorherige Seite',
    'navigateAwayMessage': 'Sie sind dabei aus Phaidra+ auszusteigen!',
    'navigateLoginMessage': '',
    'next': 'Nächste Seite',
    'results':'Ergebnisse',

    'slideshow' : "Slideshow",
    'slideshow-paralell-view' : "Parallelprojektion",
    'slideshow-single-view' : "Einzelbild",

    'help-menu-collections':'Der Arbeitsplatz bietet Zugriff auf Ihre eigenen Sammlungen und Objekte',
    'help-menu-suche':'Die Suchfunktion erlaubt Zugriff auf alle über Phaidra+ aufrufbaren digitalen Objekte',
    'help-my-collections':'Verwalten Sie Ihre Recherchen und Präsentationen über Ordner',
    'help-my-objects':'Hier sehen Sie Ihre eigenen Objekte chronologisch sortiert',
    'continue-tour':"Weiter",
    'finish-tour':"Tour beenden",

    'create-new-collection':"Neue",


    "moreentries":        "weitere Einträge",
    "deleteItem":         "Aus dem Ordner entfernen",
    'collectionsTitle':     "Meine Ordner",
    'objectsTitle':     "Meine Objekte",
    'currentObjectsTitle':    "Neue Objekte in phaidra+",
    'findObjectsTitle':     'Objekte suchen',
    'collectionAdd':      "Neu",
    'collectionAddTooltip':      "Neuen Ordner anlegen",
    'untitledCollection':      "Neuer Ordner",
    'click-to-edit':      "Anklicken, um Titel zu bearbeiten",
    'collectionOpen':       "Ordner öffnen",
    'collectionEdit' :      'Ordner bearbeiten',
    'collectionunEdit' :      'Bearbeitung beenden',
    'download-ppt' :      'Powerpoint herunterladen',

    'objectAdd':      "Neu",
    'objectAddTooltip':      "Neues Objekt in Phaidra anlegen",
    'ingest-modal-title': "Neues Objekt erstellen",
    'ingest-modal-explanation': "Neue Objekte können über den Phaidra-Uploader erstellt werden<br>Nach dem Upload warten Sie bitte 5 Minuten und laden dann diese Seite neu<br>Ihre neu angelegten Objekten finden Sie dann im Bereich 'Meine Objekte'",
    'ingest-modal-link': "zum Upload",
    
    'collectionDelete' :    'Ordner löschen',
    'delete-warning' :    "Wollen Sie diesen Ordner löschen?",

    'object' :    'Objekt',
    'objects' :     'Objekte',
    'undatedObjects' :     'Objekte ohne Zeitangaben',
    'unlocatedObjects' :     'Objekte ohne geografische Angaben',
    'objects-not-placeable':"Diese Objekte können in dieser Ansicht aufgrund fehlender Metadaten (Zeit, Ort) nicht eingeordnet werden",



    
    'metadata-categories-title':     "Kategorien",
    'metadata-copyrights-title':     "Copyrights und Lizenzen",
    'metadata-objectdata-title':     "Objektdaten",
    'metadata-otherdata-title': 'Weitere Objektdaten',
    'metadata-objecthistory-title':     "Provenienz",
    'metadata-attributions-title':      'Schlagworte',
    'myCollections':     "Meine Ordner",
    'open-in-phaidra':     "in Phaidra öffnen",
    'open-in-phaidra-temp':     "in PhaidraTemp öffnen",
    
    'open-document': 'Dokument in neuem Fenster öffnen',



    "actionsMenuAddtoCollection": "Zu einem Ordner hinzufügen",
    "actionsMenuAddtoPresention": "add this to my presentation",
    "actionsMenuCalltoAction": "Aktionen für dieses Objekt",
    "actionsMenuMarkObject": "Markieren",
    "actionsMenuUnmarkObject": "Markierung entfernen",
    "actionsMenuShowAnnotations": "Annotationen anzeigen",
    "actionsMenuShowSimilar": "Ähnliche Bilder anzeigen",
    "altTitleBefore": "Alternativ ",
    "byArtist": "von",
    "byAuthor": "Autor",
    "singleViewCloseBtnTitle": "Ansicht schließen",

    'show-title':"Titel",
    'show-desc':"Beschreibung",


    "addToCollection": "Zu Ordner hinzufügen",
    "downloadImage": "Bild herunterladen",
    "openImage": "Vollansicht",
    "markObject": "Markieren",
    "unmarkObject": "Markierung entfernen",
    "author": "Autor",
    "clearSelection": "Markierungen entfernen",
    "description": "Beschreibung",
    "display": "Anzeige",
    "displayOptions": "Darstellungsoptionen",
    "displayMode": "Darstellung",
    "filterByKeywords": "Nach Begriffen filtern",
    "filterByMarks": "Nach Markierungen filtern",
    "markAllObjects": "Alles markieren",
    "imageSize": "Bildgröße",
    "invertSelection": "Markierungen umkehren",
    "list": "Liste",
    "markedImages": "Markierte Bilder",
    "off": "Aus",
    "on": "An",
    "showAll": "Alle anzeigen",
    "tableau": "Tableau",
    "title": "Titel",


    'afterThisDate': 'jünger als',
    'alttitle' : 'Alternativer Titel',
    'author' : 'Autor',
    'beforeThisDate': 'älter als',
    'booleanAnd': 'und',
    'booleanOr': 'oder',
    "bye": "Auf Wiedersehen",
    "cancel": "Abbrechen",
    'close': 'Schließen',
    'copyright': 'Copyright',
    'costs' : 'Kosten',
    'coverage': 'Gültigkeit',
    'datapool': 'Datenpool',
    'desc': 'Beschreibung',
    'equalTo': 'gleich =',
    'filesize': 'Dateigröße',
    'filesize_human': 'Dateigröße',
    'greaterThan': 'größer als >',
    'image_height': 'Höhe (px)',
    'image_width': 'Breite (px)',
    'height': 'Höhe',
    'width': 'Breite',
    'source': 'Quelle',
    'measurement': 'Maße',
    'length': 'Länge',
    'identifiers': 'Datenkennung',
    'inscription': 'Inschrift',
    'keywords': 'Stichwörter',
    'language' :'Sprache des Objekts',
    'desc_language':"Sprache der Beschreibung",
    'upload_date':"Erstellungsdatum des digitalen Objekts",
    'title_languages':"Sprache(n) des Titels",
    'costs':"Kosten",
    'taxon':"Begriffe",
    'mimetype':"Dateityp",
    'pid':'identifiers',
    'coverage':"Zeitliche und/oder geografische Abdeckung",

    'lessThan': 'kleiner als <',
    'license': 'Lizenz',
    'login': 'Anmelden',
    'logout': 'Abmelden',
    'members': 'Mitglieder',

    'obj_date': 'Objektdatum',
    'onThisDate': 'exakt vom',
    "ok": "Ok",
    'password': 'Passwort',
    'peer_reviewed': 'peer reviewed',
    'pid': 'Permanente ID',
    'please-login': 'Bitte melden Sie sich an',
    'please-select': 'Bitte auswählen',

    'PPT-creation-explanation': 'Sie können ihren Ordner als Powerpoint Präsentation herunterladen.<br>Die Anzahl der Bilder ist hierbei auf 50 limitiert.',
    'PPT-download-title': 'Powerpoint Präsentation erstellen',
    'create-PPT': "Powerpoint erstellen",

    'query': 'Einfache Suche',
    'search-select-label': 'Neuen Suchfilter hinzufügen',
    'share-explanation': 'Nutzen Sie diesen Link um die aktuelle Ansicht zu teilen.',
    'share-modal-title': 'Ansicht teilen',
        
    'collection-modal-title': 'Objekt zu Ordner hinzufügen',

    'download-modal-title': 'Bild herunterladen',
    'download-original':"Originalbild",
    'download-original-file':"Datei herunterladen",
    'download-large':"Groß",
    'download-medium':"Mittel",
    'download-small':"Klein",
    'start-search': 'Suche starten',

    'status': 'Status',
    'subject': 'Schlagwort',
    'subtitle': 'Untertitel',
    'subtitle_de': 'Untertitel',
    'title': 'Titel',
    'title_de': 'Titel',
    'type': 'Typ',
    

    'username': 'Benutzername',


     prefixAgo: null,
      prefixFromNow: null,
      suffixAgo: "vor",
      suffixFromNow: "in",
      inPast: 'gleich',
      seconds: "weniger als eine Minute",
      minute: "ungefähr eine Minute",
      minutes: "%d Minuten",
      hour: "ungefähr eine Stunde",
      hours: "ungefähr %d Stunden",
      day: "ein Tag",
      days: "%d Tage",
      month: "ungefähr ein Monat",
      months: "%d Monate",
      year: "ungefähr ein Jahr",
      years: "%d Jahre",
      wordSeparator: " ",
      numbers: []

  },
  "en": true
});